### ISSUE TITLE
Not compatible Shapediver

### ISSUE THREAD

**Issue by alegilje** [enmerk4r/Swiftlet#17]
Error
Library Swiftlet, Version 0.1.8.0, AssemblyVersion 0.1.8.0 by Sergey Pigach may not be used yet.

**Comment by enmerk4r** [comment]
Hi @alegilje, are you using a paid version of ShapeDiver or a free version? ShapeDiver only deployed Swiftlet on their Rhino 7 backend, which is not available for free accounts
