### ISSUE TITLE
Add ByteArray content type

### ISSUE THREAD

**Issue by fraguada** [enmerk4r/Swiftlet#4]
Would allow for including a variety of data, like upoloading images:

```csharp
var image = new ByteArrayContent(File.ReadAllBytes(filePath));

var ext = Path.GetExtension(filePath);
var contentType = "image/";
if (ext.ToLower().Contains("png"))
{
    contentType += "png";
}
else if (ext.ToLower().Contains("jpg"))
{
    contentType += "jpg";
}
image.Headers.Add("Content-Type", contentType);
```
maybe there is already a way to do this?

**Comment by enmerk4r** [comment]
As we discussed off-screen, this will involve adding a new Create Body component that can read files from disk and convert them to byte arrays. Sounds like a great feature for the next release

**Comment by enmerk4r** [comment]
@fraguada I pushed a new component to the `develop` branch. It allows you to read a file from disk and create a request body with byte array contents. I managed to successfully push a PNG to a public S3 bucket. Check it out, let me know if this works for you

![image](https://user-images.githubusercontent.com/25551621/175436815-c49f4149-f2f1-469a-9c8d-ba9cb800b275.png)

**Comment by enmerk4r** [comment]
I also added components for saving binary and text files. So I've actually been able to download that image back

![image](https://user-images.githubusercontent.com/25551621/175447640-63dd6537-f92e-4a69-83cb-d90d8fe8918d.png)

**Comment by enmerk4r** [comment]
Done in #9
